package academy.pocu.comp2500.assignment2.registry;

public enum InterfaceKey {
    // stamp
    CREATE_STAMP_WITH_RED_INK,
    CREATE_STAMP_WITH_BLUE_INK,
    CREATE_STAMP_WITH_GREEN_INK,

    // calendar
    CREATE_WALL_CALENDAR,
    CREATE_MAGNET_CALENDAR,
    CREATE_DESK_CALENDAR,

    // banner
    CREATE_LANDSCAPE_BANNER,
    CREATE_PORTRAIT_BANNER,
    CREATE_GLOSS_BANNER,
    CREATE_SCRIM_BANNER,
    CREATE_MESH_BANNER,

    // business card
    CREATE_LANDSCAPE_BUSINESS_CARD,
    CREATE_PORTRAIT_BUSINESS_CARD,
    CREATE_IVORY_BUSINESS_CARD,
    CREATE_GRAY_BUSINESS_CARD,
    CREATE_WHITE_BUSINESS_CARD,
    CREATE_LAID_BUSINESS_CARD,
    CREATE_LINEN_BUSINESS_CARD,
    CREATE_SMOOTH_BUSINESS_CARD,
    CREATE_SINGLE_SIDED_BUSINESS_CARD,
    CREATE_DOUBLE_SIDED_BUSINESS_CARD,

    // cart
    CREATE_CART,
    PRODUCT_ADDER,
    PRODUCT_REMOVER,
    TOTAL_PRICE_GETTER,

    LANDSCAPE_BANNER_TEXT_APERTURE_ADDER,
    LANDSCAPE_BANNER_IMAGE_APERTURE_ADDER,
    PORTRAIT_BANNER_TEXT_APERTURE_ADDER,
    PORTRAIT_BANNER_IMAGE_APERTURE_ADDER,
    GLOSS_BANNER_TEXT_APERTURE_ADDER,
    GLOSS_BANNER_IMAGE_APERTURE_ADDER,
    SCRIM_BANNER_TEXT_APERTURE_ADDER,
    SCRIM_BANNER_IMAGE_APERTURE_ADDER,
    MESH_BANNER_TEXT_APERTURE_ADDER,
    MESH_BANNER_IMAGE_APERTURE_ADDER,

    LANDSCAPE_BUSINESS_CARD_TEXT_APERTURE_ADDER,
    LANDSCAPE_BUSINESS_CARD_IMAGE_APERTURE_ADDER,
    PORTRAIT_BUSINESS_CARD_TEXT_APERTURE_ADDER,
    PORTRAIT_BUSINESS_CARD_IMAGE_APERTURE_ADDER,
    IVORY_BUSINESS_CARD_TEXT_APERTURE_ADDER,
    IVORY_BUSINESS_CARD_IMAGE_APERTURE_ADDER,
    GRAY_BUSINESS_CARD_TEXT_APERTURE_ADDER,
    GRAY_BUSINESS_CARD_IMAGE_APERTURE_ADDER,
    WHITE_BUSINESS_CARD_TEXT_APERTURE_ADDER,
    WHITE_BUSINESS_CARD_IMAGE_APERTURE_ADDER,
    LAID_BUSINESS_CARD_TEXT_APERTURE_ADDER,
    LAID_BUSINESS_CARD_IMAGE_APERTURE_ADDER,
    LINEN_BUSINESS_CARD_TEXT_APERTURE_ADDER,
    LINEN_BUSINESS_CARD_IMAGE_APERTURE_ADDER,
    SMOOTH_BUSINESS_CARD_TEXT_APERTURE_ADDER,
    SMOOTH_BUSINESS_CARD_IMAGE_APERTURE_ADDER,
    SINGLE_SIDED_BUSINESS_CARD_TEXT_APERTURE_ADDER,
    SINGLE_SIDED_BUSINESS_CARD_IMAGE_APERTURE_ADDER,
    DOUBLE_SIDED_BUSINESS_CARD_TEXT_APERTURE_ADDER,
    DOUBLE_SIDED_BUSINESS_CARD_IMAGE_APERTURE_ADDER
}
